### ISSUE TITLE
f16v4 show freezing in player mode

### ISSUE THREAD

**Issue by sienk1mh** [Pixelcontroller/f16v4_issues#30] opened 2022-10-07 01:19 UTC
I am trying to run my show off of the micro SD card on the f16v4 and my show continually freezes, but the controller remains responsive.  It can be restarted and takes off again.  It seems a playlist will run for 10-20 minutes and randomly freeze at different points.  I have changed the SD card to a brand new card and that doesn't seem to have helped.  I was running build 21 and just installed build 22 and the problem continues.  I am using FPP upload from xlights to upload the sequences to the controller.  The sequences seem to work and then it locks.  Is there a recommended FSEQ type to be uploading to the controller, it is defaulting to v2 zlib and that is what i have been using?  Any other ideas in troubleshooting this or am I missing something?

**Comment by keithsw1111** [comment] 2022-10-10 22:21
We are going to need some files from you to try to reproduce the issue. Best to drop us a note at support@pixelcontroller.com and we can arrange a way for you to get them to us.

**Comment by keithsw1111** [comment] 2023-11-06 07:06
Closing due to age

**Closed by keithsw1111** 2023-11-06 07:06 UTC
